In [0]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/My Drive/dataset_final.csv')

In [0]:
df.head()

Unnamed: 0  Id_User Ville de depart  ...  accident  retard rating
0           0    74517           RABAT  ...         0       0      5
1           1    90486      CASABLANCA  ...         1       1      1
2           2    69046        KHENIFRA  ...         1       1      2
3           3    86417           RABAT  ...         1       1      2
4           4    79358      OUARZAZATE  ...         1       1      2

[5 rows x 29 columns]

In [0]:
df.drop(['Unnamed: 0','Ville de depart',"Ville d'arrivée"],axis=1,inplace=True)

In [0]:
#extract the categorial featuers
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

weekday_name_dep weekday_name_arr Moyen_de_transport
0          Tuesday          Tuesday            Voiture
1           Sunday           Sunday            Voiture
2           Sunday           Monday            autocar
3        Wednesday        Wednesday            autocar
4        Wednesday        Wednesday            Voiture

In [0]:
df1=pd.get_dummies(df, columns=["weekday_name_dep","weekday_name_arr","Moyen_de_transport"], prefix=["week_dep","week_arr","transport"])

In [0]:
df1

Id_User   Latitude  ...  transport_Voiture  transport_autocar
0         74517  34.022405  ...                  1                  0
1         90486  33.595063  ...                  1                  0
2         69046  32.935772  ...                  0                  1
3         86417  34.022405  ...                  0                  1
4         79358  30.920193  ...                  1                  0
...         ...        ...  ...                ...                ...
688714    76634  30.920193  ...                  1                  0
688715    93023  33.830287  ...                  1                  0
688716    99781  36.860370  ...                  0                  0
688717    93331  42.651545  ...                  1                  0
688718    68108  34.230155  ...                  0                  1

[688719 rows x 40 columns]

In [0]:
df2=df1[['Id_User','Latitude','Longitude','Latitude.1','Longitude.1','Distance','prix','Year_dep','Month_dep','day_dep','Hour_dep','minute_dep','day_arr','Hour_arr','minute_arr','hour_duree','minute_duree','nombre_place','traffic','securite','accident','retard','week_dep_Friday','week_dep_Monday','week_dep_Saturday','week_dep_Sunday','week_dep_Thursday','week_dep_Tuesday','week_dep_Wednesday','week_arr_Friday','week_arr_Monday','week_arr_Saturday','week_arr_Sunday','week_arr_Thursday','week_arr_Tuesday','week_arr_Wednesday','transport_CTM','transport_Voiture','transport_autocar','rating']]

In [0]:
df2.drop(['traffic','securite','accident','retard'],axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
df2.head(1)

Id_User   Latitude  Longitude  ...  transport_Voiture  transport_autocar  rating
0    74517  34.022405  -6.834543  ...                  1                  0       5

[1 rows x 36 columns]

In [0]:
df2.head(100).to_excel('/content/drive/My Drive/dataset_test.xlsx')

In [0]:
X = df2.iloc[:,0:35].values
y = df2.iloc[:,35].values
print('The independent features set: ')
print(X[:,0:35])


The independent features set: 
[[ 7.45170000e+04  3.40224050e+01 -6.83454300e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 9.04860000e+04  3.35950627e+01 -7.61877680e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 6.90460000e+04  3.29357718e+01 -5.66965040e+00 ...  0.00000000e+00
   0.00000000e+00  1.00000000e+00]
 ...
 [ 9.97810000e+04  3.68603699e+01  6.92500616e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 9.33310000e+04  4.26515447e+01 -1.30906530e+00 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 6.81080000e+04  3.42301550e+01 -4.01010400e+00 ...  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]


In [0]:
y

array([5, 1, 2, ..., 2, 2, 2])

In [0]:
y=keras.utils.to_categorical(y, num_classes=None, dtype='float32')

In [0]:
print(y)

[[0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [0]:

from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=0)

In [0]:
from sklearn import preprocessing

In [0]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test= min_max_scaler.fit_transform(X_test)

In [0]:
from keras import Sequential
from keras.layers import Dense
import keras
import keras.utils
from keras import utils as np_utils

In [0]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(20, activation='relu', kernel_initializer='random_normal', input_dim=35))
#Second  Hidden Layer
classifier.add(Dense(20, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(6, activation='sigmoid', kernel_initializer='random_normal'))

In [0]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])

In [0]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=10, epochs=10)

Epoch 1/10
482103/482103 [==============================] - 55s 114us/step - loss: 0.3790 - accuracy: 0.8364
Epoch 2/10
482103/482103 [==============================] - 56s 115us/step - loss: 0.2465 - accuracy: 0.8840
Epoch 3/10
482103/482103 [==============================] - 55s 114us/step - loss: 0.2216 - accuracy: 0.8898
Epoch 4/10
482103/482103 [==============================] - 56s 115us/step - loss: 0.2117 - accuracy: 0.8942
Epoch 5/10
482103/482103 [==============================] - 54s 113us/step - loss: 0.2039 - accuracy: 0.8969
Epoch 6/10
482103/482103 [==============================] - 57s 119us/step - loss: 0.1939 - accuracy: 0.8989
Epoch 7/10
482103/482103 [==============================] - 55s 114us/step - loss: 0.1844 - accuracy: 0.9005
Epoch 8/10
482103/482103 [==============================] - 56s 116us/step - loss: nan - accuracy: 0.4375
Epoch 9/10
482103/482103 [==============================] - 55s 115us/step - loss: nan - accuracy: 0.0785
Epoch 10/10
482103/482103

In [0]:
eval_model = classifier.evaluate (X_train, y_train) 
eval_model

482103/482103 [==============================] - 8s 17us/step


[nan, 0.0784500390291214]

In [0]:
score,acc= classifier.evaluate (X_test, y_test) 


206616/206616 [==============================] - 3s 17us/step


In [0]:
print(acc)

0.07810624688863754


In [0]:
# Load libraries
import numpy as np
from keras import models
from keras import layers
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [0]:
# K fold validation
def build_classifier():
    classifier = Sequential()
    #First Hidden Layer
    classifier.add(Dense(24, activation='relu', kernel_initializer='random_uniform', input_dim=35))
    
    #Second  Hidden Layer
    classifier.add(Dense(24, activation='relu', kernel_initializer='random_uniform'))
#Output Layer
    classifier.add(Dense(6, activation='softmax', kernel_initializer='random_uniform'))
#Compiling the neural network
    classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])
    return classifier

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
classifier.fit(X_train,y_train, batch_size=10, epochs=15)

Epoch 1/15
482103/482103 [==============================] - 55s 115us/step - loss: nan - accuracy: 0.0785
Epoch 2/15
482103/482103 [==============================] - 56s 116us/step - loss: nan - accuracy: 0.0785
Epoch 3/15
482103/482103 [==============================] - 56s 116us/step - loss: nan - accuracy: 0.0785
Epoch 4/15
482103/482103 [==============================] - 56s 116us/step - loss: nan - accuracy: 0.0785
Epoch 5/15
482103/482103 [==============================] - 57s 117us/step - loss: nan - accuracy: 0.0785
Epoch 6/15
482103/482103 [==============================] - 56s 117us/step - loss: nan - accuracy: 0.0785
Epoch 7/15
482103/482103 [==============================] - 56s 116us/step - loss: nan - accuracy: 0.0785
Epoch 8/15
482103/482103 [==============================] - 55s 115us/step - loss: nan - accuracy: 0.0785
Epoch 9/15
482103/482103 [==============================] - 55s 115us/step - loss: nan - accuracy: 0.0785
Epoch 10/15
482103/482103 [===================

In [0]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, nb_epoch=15)

In [0]:
accuracy =  cross_val_score(estimator=classifier, X= X, y=y,cv=5, n_jobs=-1)
accuracy

array([0.56498289, 0.76800442, 0.70861161, 0.78171825, 0.7518785 ])

In [0]:
print(accuracy.mean())
print(accuracy.std())

0.7150391340255737
0.07895157290951355


In [0]:
classifier.fit(X_train, y_train)

Epoch 1/1
482103/482103 [==============================] - 52s 109us/step - loss: 0.3488 - accuracy: 0.8563


In [0]:
y=classifier.predict(np.array([[74517,34.022405,-6.834543,33.595063,-7.618777,92.718000,30,2018,7,31,23,31,31,0,38,1,7,4,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1]]))


In [0]:
print(y)

[1]


In [0]:
y=classifier.predict([[74517,34.022405,-6.834543,33.595063,-7.618777,92.718000,18.54360,2018,7,31,21,31,31,22,38,1,7,4,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0]])

ValueError: ignored

In [0]:
y

In [0]:
from keras.layers import Activation
from keras import backend as K
from keras.utils.generic_utils import get_custom_objects

def swish(x):
    return (K.sigmoid(x) * x)

get_custom_objects().update({'swish': Activation(swish)})

In [0]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(40, activation='swish', kernel_initializer='random_normal', input_dim=35))
#Second  Hidden Layer
classifier.add(Dense(40, activation='swish', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(6, activation='swish', kernel_initializer='random_normal'))

In [0]:
#Compiling the neural network
    classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])

In [0]:
df2.head()

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
classifier.fit(X_train,y_train, batch_size=10, epochs=10)

In [0]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(55, activation='swish', kernel_initializer='random_normal', input_dim=35))
#Second  Hidden Layer
classifier.add(Dense(55, activation='swish', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(6, activation='swish', kernel_initializer='random_normal'))
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
classifier.fit(X_train,y_train, batch_size=10, epochs=10)

In [0]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(44, activation='swish', kernel_initializer='random_normal', input_dim=35))
#Second  Hidden Layer
classifier.add(Dense(44, activation='swish', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(6, activation='swish', kernel_initializer='random_normal'))
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
classifier.fit(X_train,y_train, batch_size=10, epochs=10)

In [0]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(42, activation='swish', kernel_initializer='random_normal', input_dim=35))
#Second  Hidden Layer
classifier.add(Dense(42, activation='swish', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(6, activation='swish', kernel_initializer='random_normal'))
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])
from keras.wrappers.scikit_learn import KerasClassifier
classifier.fit(X_train,y_train, batch_size=10, epochs=10)

In [0]:
# K fold validation
def build_classifier():
    classifier = Sequential()
    #First Hidden Layer
    classifier.add(Dense(40, activation='swish', kernel_initializer='random_uniform', input_dim=35))
    
    #Second  Hidden Layer
    classifier.add(Dense(40, activation='swish', kernel_initializer='random_uniform'))
#Output Layer
    classifier.add(Dense(6, activation='softmax', kernel_initializer='random_uniform'))
#Compiling the neural network
    classifier.compile(optimizer ='adam',loss='categorical_crossentropy', metrics =['accuracy'])
    return classifier

In [0]:
classifier.fit(X_train,y_train, batch_size=10, epochs=10)


In [0]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, nb_epoch=10)

In [0]:
scores = cross_val_score(classifier, X, y, cv=5)

In [0]:
print(scores.mean())
