In [103]:
import pandas as pd
import os
import matplotlib.pyplot as plt
os.chdir ("C:\\Users\\Hp\\Desktop\\Chaimae\\stage\\PFE\\Dataset\\clean_data")
cwd=os.getcwd()
print(cwd)
df=pd.read_excel('dataprepro.xlsx')

C:\Users\Hp\Desktop\Chaimae\stage\PFE\Dataset\clean_data


In [104]:
df.head()

Id_User Ville de depart   Latitude  Longitude Ville d'arrivée  Latitude.1  \
0    74517           RABAT  34.022405  -6.834543      CASABLANCA   33.595063   
1    90486      CASABLANCA  33.595063  -7.618777            TAZA   34.230155   
2    69046        KHENIFRA  32.935772  -5.669650          AGADIR   30.422037   
3    86417           RABAT  34.022405  -6.834543         TETOUAN   35.570175   
4    79358      OUARZAZATE  30.920193  -6.910923          TEMARA   33.917166   

   Longitude.1    Distance      prix  Year_dep  ...  Hour_dep  minute_dep  \
0    -7.618777   92.718000   18.5436      2018  ...        21          31   
1    -4.010104  403.209999   80.6420      2018  ...        11          12   
2    -9.559509  649.335999  194.8008      2018  ...         6          24   
3    -5.374278  270.819000   81.2457      2018  ...         6           0   
4    -6.923804  509.914999  142.7762      2018  ...        15          30   

  day_arr  weekday_name_arr  minute_arr  Hour_arr hour_duree  minute_duree  \
0      31           Tuesday          31        21          1             7   
1      29            Sunday          12        11          3            50   
2      15            Sunday          24         6         19            29   
3       5         Wednesday           0         6          9            33   
4      23         Wednesday          30        15          5            39   

   nombre_place  Moyen_de_transport  
0             4             Voiture  
1             2             Voiture  
2             2             Voiture  
3             2             Voiture  
4             4             Voiture  

[5 rows x 23 columns]

In [108]:
df.drop(['Ville de depart','Latitude','Longitude',"Latitude.1","Longitude.1","Ville d'arrivée",'weekday_name_dep',"weekday_name_arr"],axis=1,inplace=True)

In [105]:
df.isnull().sum().sum()

0

In [106]:
from sklearn import preprocessing
import numpy as np
# Import the encoder from sklearn
le = preprocessing.LabelEncoder()

# Encode the features
df['encoded_ville_dep']=le.fit_transform(df['Ville de depart'])
df['encoded_ville_arr']=le.fit_transform(df["Ville d'arrivée"])
df['encoded_weekday_name_dep']=le.fit_transform(df['weekday_name_dep'])
df['encoded_weekday_name_arr']=le.fit_transform(df['weekday_name_arr'])

In [109]:
df.head()

Id_User    Distance      prix  Year_dep  Month_dep  day_dep  Hour_dep  \
0    74517   92.718000   18.5436      2018          7       31        21   
1    90486  403.209999   80.6420      2018          4       29        11   
2    69046  649.335999  194.8008      2018          7       15         6   
3    86417  270.819000   81.2457      2018         12        5         6   
4    79358  509.914999  142.7762      2018          5       23        15   

   minute_dep  day_arr  minute_arr  Hour_arr  hour_duree  minute_duree  \
0          31       31          31        21           1             7   
1          12       29          12        11           3            50   
2          24       15          24         6          19            29   
3           0        5           0         6           9            33   
4          30       23          30        15           5            39   

   nombre_place Moyen_de_transport  encoded_ville_dep  encoded_ville_arr  \
0             4            Voiture                 22                  5   
1             2            Voiture                  5                 28   
2             2            Voiture                 13                  0   
3             2            Voiture                 22                 30   
4             4            Voiture                 19                 29   

   encoded_weekday_name_dep  encoded_weekday_name_arr  
0                         5                         5  
1                         3                         3  
2                         3                         3  
3                         6                         6  
4                         6                         6

In [91]:
df.isnull().sum().sum()

0

In [110]:
#Creating the dependent variable class
factor = pd.factorize(df['Moyen_de_transport'])
df.Moyen_de_transport = factor[0]
definitions = factor[1]
print(df.Moyen_de_transport.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: Moyen_de_transport, dtype: int64
Index(['Voiture', 'CTM', 'autocar'], dtype='object')


In [111]:
df1=df[['Id_User','encoded_ville_dep','encoded_ville_arr','Distance','prix','Year_dep','Month_dep','day_dep','encoded_weekday_name_dep','Hour_dep','minute_dep','day_arr','encoded_weekday_name_arr','minute_arr','Hour_arr','hour_duree','minute_duree','nombre_place','Moyen_de_transport']]

In [160]:
df1

Id_User  encoded_ville_dep  encoded_ville_arr     Distance       prix  \
0         74517                 22                  5    92.718000   18.54360   
1         90486                  5                 28   403.209999   80.64200   
2         69046                 13                  0   649.335999  194.80080   
3         86417                 22                 30   270.819000   81.24570   
4         79358                 19                 29   509.914999  142.77620   
5         88786                  8                 28   770.075000  192.51875   
6         95432                 20                 30   127.446999   35.68516   
7         73903                 19                  2   299.233000   83.78524   
8         98425                  5                 19   437.146000  196.71570   
9         93117                 19                  2   299.233000  134.65485   
10        96719                  4                  7   591.270000  266.07150   
11        73280                  6                 21   710.254000  142.05080   
12        80519                 17                 19   459.326000  137.79780   
13        98958                  8                 21   980.945000  294.28350   
14        13336                  6                 10   382.694000  107.15432   
15        30213                 14                 22   208.590999   52.14775   
16        49455                  5                 22    92.925000   18.58500   
17        99552                 15                  8   174.899000   78.70455   
18        33912                 22                 27   248.345000   49.66900   
19        64796                 29                  4   114.127999   22.82560   
20        71094                 13                 12   171.472000   48.01216   
21        67045                 13                  3   485.136000  135.83808   
22        87940                  8                 27   711.917000  213.57510   
23        98233                  8                 15   174.962001   48.98936   
24        48079                 16                 28   173.115999   51.93480   
25        71140                  4                 26   259.677999   51.93560   
26        51029                 14                 18   591.152000  266.01840   
27        98590                 13                  3   485.136000   97.02720   
28        97876                 30                 13   382.985000  114.89550   
29        98100                  3                  5   610.013000  152.50325   
...         ...                ...                ...          ...        ...   
688689    33912                 18                 10  1043.274000  469.47330   
688690    91720                  4                  6   101.220000   20.24400   
688691    60202                  2                 25   217.455001   43.49100   
688692    84764                 29                 14   138.085000   41.42550   
688693    82975                 20                  4   307.269000   92.18070   
688694    68111                  1                 14   558.444000  156.36432   
688695    86954                  4                  5    39.395000    9.84875   
688696    55981                  6                 10   382.694000  114.80820   
688697     9948                  8                  1   925.049999  185.01000   
688698    85511                 11                 16   146.035000   40.88980   
688699    44508                  4                  1   589.680001  265.35600   
688700    95249                 26                 15   462.358000  129.46024   
688701    99825                 13                  5   262.693001  118.21185   
688702    92576                  5                  8   374.895999   74.97920   
688703    99037                 30                  9   349.205000   97.77740   
688704    44799                 29                  3   524.187000  235.88415   
688705    85547                 15                  0   247.197001   49.43940   
688706    88587                  8     

In [164]:
#Importing Libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

In [165]:
X = df1.iloc[:,1:18].values
y = df1.iloc[:,18].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:18])

The independent features set: 
[[2.20000000e+01 5.00000000e+00 9.27179997e+01 1.85435999e+01
  2.01800000e+03 7.00000000e+00 3.10000000e+01 5.00000000e+00
  2.10000000e+01 3.10000000e+01 3.10000000e+01 5.00000000e+00
  3.10000000e+01 2.10000000e+01 1.00000000e+00 7.00000000e+00
  4.00000000e+00]
 [5.00000000e+00 2.80000000e+01 4.03209999e+02 8.06419999e+01
  2.01800000e+03 4.00000000e+00 2.90000000e+01 3.00000000e+00
  1.10000000e+01 1.20000000e+01 2.90000000e+01 3.00000000e+00
  1.20000000e+01 1.10000000e+01 3.00000000e+00 5.00000000e+01
  2.00000000e+00]
 [1.30000000e+01 0.00000000e+00 6.49335999e+02 1.94800800e+02
  2.01800000e+03 7.00000000e+00 1.50000000e+01 3.00000000e+00
  6.00000000e+00 2.40000000e+01 1.50000000e+01 3.00000000e+00
  2.40000000e+01 6.00000000e+00 1.90000000e+01 2.90000000e+01
  2.00000000e+00]
 [2.20000000e+01 3.00000000e+01 2.70819000e+02 8.12457000e+01
  2.01800000e+03 1.20000000e+01 5.00000000e+00 6.00000000e+00
  6.00000000e+00 0.00000000e+00 5.00000000e+00 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [135]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [166]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [167]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test= min_max_scaler.fit_transform(X_test)

In [168]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=40)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

In [169]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9941630851434545


In [35]:
print(list(zip(df1.columns[1:22], clf.feature_importances_)))

[('encoded_ville_dep', 0.004979357772516958), ('Latitude', 0.007903075705476489), ('Longitude', 0.007453220566030753), ('encoded_ville_arr', 0.004842990780493848), ('Latitude.1', 0.007343114058591558), ('Longitude.1', 0.0072185837018051355), ('Distance', 0.05875399453909215), ('prix', 0.10519497155007503), ('Year_dep', 0.0003477891305983939), ('Month_dep', 0.0019035043923167913), ('day_dep', 0.002174982733850535), ('encoded_weekday_name_dep', 0.0012825165599608143), ('Hour_dep', 0.001892419750115616), ('minute_dep', 0.0026024159972581166), ('day_arr', 0.0021632518426080677), ('encoded_weekday_name_arr', 0.0012784991942322607), ('minute_arr', 0.0025581762490615952), ('Hour_arr', 0.0018946841957039064), ('hour_duree', 0.1970252007812246), ('minute_duree', 0.012673573184337384), ('nombre_place', 0.5685136773146501)]


In [148]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=5)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [149]:
from sklearn.model_selection import StratifiedKFold

In [150]:
score_clf=[]
clf=RandomForestClassifier(n_estimators=40)
for train_index,test_index,in kf.split(X):
    X_train,X_test,y_train,y_test= X[train_index],X[test_index],y[train_index],y[test_index]
    print(get_score(clf,X_train,X_test,y_train,y_test))

    

0.9999782204669532
0.9999637007782554
0.9999927401556511
0.971004181670345
0.9999491807206173


In [171]:
y=clf.predict(np.array([[21,23,854.498999,256.34970,2019,1,22,5,19,48,22,5,48,19,23,6,33]]))
print(y[0])

2


array([0, 0, 0, ..., 1, 0, 2], dtype=int64)

5

5